apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'deploy-service'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: deploy-service
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "2112"
            action: keep

      - job_name: 'container-service'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: container-service
            action: keep
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            regex: "2112"
            action: keep

