apiVersion: v1
kind: Service
metadata:
  name: container-service-svc
  namespace: sparrow-vps
spec:
  selector:
    app: container-service
  ports:
  - protocol: TCP
    name: http-api
    port: 8001         # existing app port
    targetPort: 8001
    nodePort: 30081

  # -----------------------------------------------------------------------
  # What: Expose Prometheus metrics on the Service.
  # Why:  To make the metrics accessible to Prometheus via the Service DNS/IP.
  # How:  Maps Service port 2112 to container port 2112.
  #       Also opens NodePort 32112 for external access (e.g., development).
  # -----------------------------------------------------------------------
  # Metrics port configuration
  - protocol: TCP
    port: 2112
    targetPort: 2112
    name: metrics
    nodePort: 32112
  type: NodePort
